### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#16]
I'm a sucker for software testing. I want to add some tests here, but probably not the priority for now. Do send a PR to `develop` branch about adding some tests, you can use [mocha](https://github.com/mochajs/mocha) and [chai](https://github.com/chaijs/chai). ✨

**Comment by ZakkMan** [comment]
I can do this one!

**Comment by igorgcosta** [comment]
Hi, I have sent the PR, please review. Any doubts contact me

**Comment by grikomsn** [comment]
Thanks for the PR, @igorgcosta! I'll check it asap. ✨

@ZakkMan you can check @igorgcosta's PR at #18.

**Comment by grikomsn** [comment]
Hey there, @jbbn. Great approach on the testings! You could submit PRs for all your branches if you want, since the latest commit is on the `develop` branch. I'll review them and also the Travis CI will detect and check your PR if it works.

Since I'm quite new to JS testing libraries, which test lib would you recommend? I've tried `mocha` and `chai` but haven't tried others.

**Comment by jbbn** [comment]
@grikomsn TravisCI trolled me :rofl: 

We need I higher version of NodeJS

**Comment by grikomsn** [comment]
> @grikomsn TravisCI trolled me 🤣
> 
> We need I higher version of NodeJS

Just read the documentation on [specifying Node.js version](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions), and I think #21 only adds a language type on the configuration. I'll update the config after this. 😅

**Comment by grikomsn** [comment]
@jbbn, I have no idea how to trigger the build with the latest configuration. So I kinda messed up the PR and the branches. Can you help? 😅

**Comment by jbbn** [comment]
@grikomsn I made an empty commit to trigger the BUT my branch was not up-to-date with `develop`.

I had to rewrite some tests. (This time I was not able to get the 100% coverage again - but I will try to achieve this later)

Now, everything seems ok:

![screenshot from 2018-10-14 02-29-59](https://user-images.githubusercontent.com/3846247/46912928-2388b180-cf59-11e8-99c9-8d03060d9b0e.png)

**Comment by grikomsn** [comment]
@jbbn, what's the difference between three PRs (#22, #23, and #24)? I'll check the branch after this.

**Comment by jbbn** [comment]
@grikomsn 

The differences can be clearly seen here:

- https://github.com/grikomsn/rotten-reviews/compare/develop...jbbn:testing-with-jest
- https://github.com/jbbn/rotten-reviews/compare/jbbn:testing-with-jest...jbbn:testing-with-jest-part2-cucumber
- https://github.com/jbbn/rotten-reviews/compare/jbbn:testing-with-jest-part2-cucumber...jbbn:feature/roadmap-error-handling-movie-doesnt-exist

I've used a "technique" called Stacked Pull Requests - I use this often, to simplify the commits and pull one feature at time (that generally depends on code that are not in the base code yet) - but it was the first time that I had no access to create branchs in the repository.

So to clarify, you should accept, firstly #22 an then #23.

The #24 is actually a work-in-progress, and I am not sure if I will finish it, because, I think it already be implemented. (Maybe I just implement the E2E tests, if you agree with #23)

** Note **: When you accept # 22, the differences with # 23 will be much smaller. (as you can see here: https://github.com/jbbn/rotten-reviews/compare/jbbn:testing-with-jest...jbbn:testing-with-jest-part2-cucumber)

* More about Stacked Pull Requests here: https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/

**And thanks for all your attention** :)

(I am sorry if I wrote something wrong in english, I'm a learner)

**Comment by grikomsn** [comment]
Thank you for the very detailed explanation, and it's my first time knowing about stacked PRs. How I learned a lot on this year's Hacktoberfest! Anyhow, I'll check on it as soon as I'm done with other works. 🎉

**Comment by grikomsn** [comment]
@jbbn I have invited you to be a repository collaborator, do check your invite: https://github.com/grikomsn/rotten-reviews/invitations

**Comment by jbbn** [comment]
Awesome @grikomsn !

Really grateful by your invitation :)

I accepted the invitation and will continue to contribute to the repository :fist_oncoming: 

I saw that you invite me to gitter too, it will be great to do some alignments there.
